apiVersion: v1
kind: Service
metadata:
  name: er-automobiles-service
  namespace: default
  labels:
    app: er-automobiles
spec:
  type: LoadBalancer
  ports:
    - name: "http"
      port: 8080
      targetPort: 8080
  selector:
    app: er-automobiles