apiVersion: v1
kind: Secret
metadata:
  name: eli-automobiles-secret
  namespace: default
type: Opaque
data:
  ##Encoded Values
  database_user: ZWxpamFoX3J1dGVy
  database_password: ZkJaRHFhblRzT0E3Tg==